---
services:
  bittorrent-client:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    networks:
      webproxy-backend:
        ipv4_address: "10.254.0.14"
    volumes:
      - ./appdata:/config
      - ./downloads:/downloads
      - ../streaming-media:/media
    ports:
#      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
