---
services:
  dynamic-dns:
    image: jbbodart/gandi-livedns
    container_name: gandi-dns
    network_mode: host #optional
    environment:
      - GANDI_PAT=${GANDIV5_PERSONAL_ACCESS_TOKEN}
      - RECORD_LIST=${RECORD_LIST}
      - DOMAIN=${DOMAIN}
    restart: unless-stopped
