---
services:
  stream-server:
    image: jellyfin/jellyfin:10.11
    container_name: jellyfin
    restart: 'unless-stopped'
    user: 1000:1000
    networks:
      webproxy-backend:
        ipv4_address: "10.254.0.11"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ../streaming-media:/media
